apiVersion: apps/v1
kind: Deployment
metadata:
    name: argo-app-nfs
spec:
    replicas: 2
    selector:
      matchLabels:
        app: argo-app-nfs
    template:
      metadata:
        labels:
          app: argo-app-nfs
      spec:
        volumes:
          - name: nfs-nginx
            persistentVolumeClaim:
              claimName: nfs-pvc-two
        containers:
          - name: nginx
            image: nginx:latest
            volumeMounts:
             - name: nfs-nginx
               mountPath: /usr/share/nginx/html  
            ports:
              - containerPort: 80
