apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: nfs-pvc-two
spec:
   accessModes:
       - ReadWriteMany
   storageClassName: nfs-client
   resources:
        requests:
          storage: 1Gi

